### ISSUE TITLE
Drop Julia 0.4 and 0.5 support

### ISSUE THREAD

**Issue by mpastell** [JuliaDocs/Highlights.jl#14]
I use this package for syntax highlighting in Weave.jl and it would be nice to get rid off deprecation warnings for 0.6 (and for coming 0.7/1.0). It seems that FemtoCleaner could fix current deprecation warnings. Could you run it on this repo? 

I can take a look at the potential errors if something needs to be handled manually.

**Comment by mortenpi** [comment]
Femtocleaner is enabled on this repo and I pushed a commit dropping 0.4 and 0.5 (https://github.com/JuliaDocs/Highlights.jl/commit/cf34985c0f26545587850816fb515c90afcd3ea7). As far as I can tell this should cause Femtocleaner to run on the repo now.

In any case, with or without Femtocleaner, if you'd be willing to help with bringing this up to date with Julia 0.6/7, then that would be much appreciated. I'd be happy to review the PRs and tag a new release.

**Comment by mortenpi** [comment]
Fixed by #16.
