### ISSUE TITLE
Release for Julia 1.0

### ISSUE THREAD

**Issue by Nosferican** [JuliaDocs/Highlights.jl#20]
Leaving issue to track progress.

**Comment by mortenpi** [comment]
With #19 in, we're ready for a Julia 1.0 release, right? Or is there something else that should be fixed that I am missing?

**Comment by Nosferican** [comment]
I just checked the master version on Julia 1.0 and it has all tests passing. A PR with minor commits to update the REQUIRE, bump version, add `Project.toml`, update CI scripts should get it all ready to tag/release it.

**Comment by mortenpi** [comment]
Well `REQUIRE` is already at `0.7.0-beta2` and the CI scripts are up to date. `Project.toml` will come with an automated PR in the future, right?

**Comment by Nosferican** [comment]
- `.travis.yml`: you could drop 0.7 and nightly for now.
- `REQUIRE`: probably dump to `julia 1.0` since `0.7.0-beta2` doesn't include 1.0 in the near future [semver](https://docs.julialang.org/en/latest/stdlib/Pkg/#Version-specifier-format-1)
- `README`: PackageEvaluator.jl is deprecated and update project status

The `Project.toml` will likely happen with an auto PR, but it will be nice to add metadata to it when it comes.

**Comment by mpastell** [comment]
I think it's better to keep 0.7 as the julia version in REQUIRE, the package will also install on all versions greater than that. You really want to have the same version of packages on 0.7 and 1.0 when upgrading other packages. 

Also why would you drop nightly on travis? You'll anyway want to have it in the future.

**Comment by mortenpi** [comment]
The semantics of a REQUIRE file are different from `Project.toml`'s. I would guess that the automatically generated Project.toml will exactly have `julia = "≥ <ver-in-REQUIRE>"`, as to be a direct replacement to the REQUIRE files. In any case, as long as the package supports 1.0, it should also be installable on 0.7 (e.g. to allow packages depending on Highlights to run on 0.7 as they do their upgrade).

No harm in keeping the nightlies going. In fact it might reveal some subtle bugs as Julia internals are updated. Currently the nightlies are allowed to fail, but I am actually thinking that they should maybe be mandatory.

PackageEvaluator is a good point. I will update the README and then tag a version.
