### ISSUE TITLE
JuliaConsoleLexer produces wrong output for Array

### ISSUE THREAD

**Issue by sebastianpech** [JuliaDocs/Highlights.jl#28]
The JuliaConsoleLexer adds some extra braces to the output part of the following code.

```
highlight(stdout,MIME("text/latex"),"""julia> [1,2,3]
       3-element Array{Int64,1}:
        1
        2
        3""",Highlights.Lexers.JuliaConsoleLexer)
```
Which gives this latex code:
```
\begin{lstlisting}
(*@\HLJLnB{julia> }@*)(*@\HLJLp{[}@*)(*@\HLJLni{1}@*)(*@\HLJLp{,}@*)(*@\HLJLni{2}@*)(*@\HLJLp{,}@*)(*@\HLJLni{3}@*)(*@\HLJLp{]}@*)
3-element Array{\{}Int64,1{\}}:
 1
 2
 3
\end{lstlisting}
```
![image](https://user-images.githubusercontent.com/13043943/62542142-7e2e2980-b85b-11e9-8828-881c92945e87.png)

**Comment by sebastianpech** [comment]
I think there is a problem with the escaping in the [render method](https://github.com/JuliaDocs/Highlights.jl/blob/18fb710f9bbd18f8043b5939d9f7bcbafdc6d13c/src/Format.jl#L202) for latex. The `3-element ...` part is escaped by
```
char === '{'  ? print(io, "{\\{}") :
char === '}'  ? print(io, "{\\}}") :
```
but not encapsulated with `(*@ ... @*)`, so it actually needs no escaping because of the verbatim environment it's in. I will further test this.

I came here because of JunoLab/Weave.jl#236 which seems to be an escaping issue as well. Maybe both can be solved by handling the rendering differently. I'll look into that.

**Comment by mortenpi** [comment]
I agree. The text tokens (or whatever `id === :t` means) should not be escaped. Things like these are also broken (we end up with literal `\textquotesingle` in the output):

```
julia> highlight(stdout,MIME("text/latex"),"function foo('x')",Highlights.Lexers.JuliaConsoleLexer)
\begin{lstlisting}
function foo({\textquotesingle}x{\textquotesingle})
\end{lstlisting}
```

I think this has been not surfaced earlier because for the main Julia lexer, most non-trivial stuff is wrapped in a non-text token.
