### ISSUE TITLE
Deploying docs fails due to incorrect permission of key

### ISSUE THREAD

**Issue by KristofferC** [JuliaDocs/Highlights.jl#32]
https://travis-ci.org/JuliaDocs/Highlights.jl/jobs/564651613#L323-L354

**Comment by mortenpi** [comment]
Good catch.. I guess it has always been read-only. @fredrikekre, could you have @zeptodoctor re-add the key?

**Comment by fredrikekre** [comment]
Should be fixed now, restarted the build on master.

**Comment by KristofferC** [comment]
Will that push the latest release doc build as well? Maybe should restart that build?

**Comment by mortenpi** [comment]
Done.
